// <auto-generated />
using System;
using AccountProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AccountProject.Data.Migrations
{
    [DbContext(typeof(SqlDbContext))]
    [Migration("20220507195034_AddedFirstMigration")]
    partial class AddedFirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AccountProject.Data.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("HesapTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("HesaplamaTürü")
                        .HasColumnType("int");

                    b.Property<int>("KdvOranId")
                        .HasColumnType("int");

                    b.Property<decimal>("SonEndeks")
                        .HasColumnType("decimal(5,3)")
                        .HasMaxLength(250);

                    b.Property<decimal>("TarifeBirimFiyat")
                        .HasColumnType("decimal(5,3)")
                        .HasMaxLength(50);

                    b.Property<int>("TarifeBirimId")
                        .HasColumnType("int");

                    b.Property<decimal>("TarifeKdvFiyat")
                        .HasColumnType("decimal(5,3)")
                        .HasMaxLength(100);

                    b.Property<decimal>("TarifeToplamFiyat")
                        .HasColumnType("decimal(5,3)")
                        .HasMaxLength(150);

                    b.Property<decimal>("İlkEndeks")
                        .HasColumnType("decimal(5,3)")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("Account");
                });
#pragma warning restore 612, 618
        }
    }
}
