// <auto-generated />
using System;
using AccountProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AccountProject.Data.Migrations
{
    [DbContext(typeof(SqlDbContext))]
    partial class SqlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AccountProject.Data.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("HesapTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("HesaplamaTürü")
                        .HasColumnType("int");

                    b.Property<int>("KdvOranId")
                        .HasColumnType("int");

                    b.Property<decimal>("SonEndeks")
                        .HasColumnType("decimal(5,3)");

                    b.Property<decimal>("TarifeBirimFiyat")
                        .HasColumnType("decimal(5,3)");

                    b.Property<int>("TarifeBirimId")
                        .HasColumnType("int");

                    b.Property<decimal>("TarifeKdvFiyat")
                        .HasColumnType("decimal(5,3)");

                    b.Property<decimal>("TarifeToplamFiyat")
                        .HasColumnType("decimal(5,3)");

                    b.Property<decimal>("İlkEndeks")
                        .HasColumnType("decimal(5,3)");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("AccountProject.Data.Entities.Subscriber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AcilisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("AdSoyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KdvOranId")
                        .HasColumnType("int");

                    b.Property<string>("Numara")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TarifeBirimId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Subscribers");
                });
#pragma warning restore 612, 618
        }
    }
}
